### ISSUE TITLE
Unit test failures

### ISSUE THREAD

**Issue by roehling** [kellyjonbrazil/jello#22]
I got one failed test while trying to package jello for Debian:

```
======================================================================
FAIL: test_dict_html (tests.test_create_json.MyTests)
Test self.dict_sample html output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/jello-1.4.2/.pybuild/cpython3_3.9_jello/build/tests/test_create_json.py", line 450, in test_dict_html
    self.assertEqual(self.json_out.html_output(output), self.expected)
AssertionError: '<div[72 chars]125%; margin: 0;"><span></span>{\n  <span styl[1171 chars]v>\n' != '<div[72 chars]125%;"><span></span>{\n  <span style="color: #[1160 chars]v>\n'
Diff is 1505 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 188 tests in 0.314s

FAILED (failures=1)
```
It looks like the `HtmlFormatter` class in Pygments 2.7.1 adds an additional `margin: 0` property to the `<pre>` style.

**Comment by kellyjonbrazil** [comment]
Ah interesting - I've been testing with Pygments 2.9.0. I wonder if it makes sense for me to add a conditional in the unit test for output from both versions? I hope there aren't changes for too many Pygments versions. :)

**Comment by roehling** [comment]
If that particular test is not very important for functionality, I can disable it for now.

**Comment by kellyjonbrazil** [comment]
Right on - that sounds good.

**Comment by roehling** [comment]
Just FYI, I'll go ahead and upload 1.4.2 to Debian anyway, because it's not a critical problem and new packages have to pass FTP master review, which can take anywhere from days to weeks.

**Comment by kellyjonbrazil** [comment]
Thank you!

**Comment by kellyjonbrazil** [comment]
FYI, according to they Pygments changelog (https://pygments.org/docs/changelog/) it seems the `margin: 0` was removed in v2.7.3.

**Comment by roehling** [comment]
Well then it was (good|bad) luck that we ran into this issue, because Pygments would likely have been updated to 2.9.0 already if it were not for the ongoing Bullseye release freeze.

**Comment by roehling** [comment]
I've seen a few more test failures like this in our CI on a non-amd64 system:

```
======================================================================
FAIL: test_twitter_lines_table (tests.test_main.MyTests)
Test cat twitterdata.jlines | jello -l '                                      user_ids = set()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/python-team/packages/jello/debian/output/source_dir/.pybuild/cpython3_3.9_jello/build/tests/test_main.py", line 3248, in test_twitter_lines_table
    self.assertEqual(f.getvalue(), self.expected)
AssertionError: '{"us[4654 chars]_id":1330235048,"user_name":"yourborwhore","us[9531 chars]"}\n' != '{"us[4654 chars]_id":2858607784,"user_name":"Data_Institute","[9531 chars]"}\n'
Diff is 15324 characters long. Set self.maxDiff to None to see it.
======================================================================
FAIL: test_twitter_lines_table_dot (tests.test_main.MyTests)
Test cat twitterdata.jlines | jello -l '                                      user_ids = set()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/python-team/packages/jello/debian/output/source_dir/.pybuild/cpython3_3.9_jello/build/tests/test_main.py", line 3346, in test_twitter_lines_table_dot
    self.assertEqual(f.getvalue(), self.expected)
AssertionError: '{"us[4654 chars]_id":1330235048,"user_name":"yourborwhore","us[9531 chars]"}\n' != '{"us[4654 chars]_id":2858607784,"user_name":"Data_Institute","[9531 chars]"}\n'
Diff is 15324 characters long. Set self.maxDiff to None to see it.
======================================================================
FAIL: test_twitter_lines_table_schema (tests.test_main.MyTests)
Test cat twitterdata.jlines | jello -s '                                      user_ids = set()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/python-team/packages/jello/debian/output/source_dir/.pybuild/cpython3_3.9_jello/build/tests/test_main.py", line 3297, in test_twitter_lines_table_schema
    self.assertEqual(f.getvalue(), self.expected)
AssertionError: '.[0][5924 chars]id = 1330235048;\n.[45].user_name = "yourborwh[12309 chars]";\n' != '.[0][5924 chars]id = 2858607784;\n.[45].user_name = "Data_Inst[12309 chars]";\n'
Diff is 21507 characters long. Set self.maxDiff to None to see it.
----------------------------------------------------------------------
```
I suspect this happens because iterating over set elements as in `for user in user_ids` has no guaranteed order. I usually throw a `sorted()` into the mix to make the output stable/predictable.

**Comment by kellyjonbrazil** [comment]
Good call - let me try that out. Sorry for all the trouble!

**Comment by roehling** [comment]
It's no trouble at all. The way I see it, all problems we catch now won't bite us later. 🙂

**Comment by kellyjonbrazil** [comment]
For sure - I have updated the `master` branch with the sorted set and updated test fixtures. Would you like me to release as v1.4.3 to pypi now or hold off in case we find some more issues?

**Comment by roehling** [comment]
I guess you can go ahead and release 1.4.3, because I'm pretty much done with packaging and would just cherry-pick your test fix commit as patch otherwise.

**Comment by kellyjonbrazil** [comment]
Sounds good - should only take a few minutes. Hopefully all of the uncovered issues so far will be addressed.

**Comment by kellyjonbrazil** [comment]
Ok, v1.4.3 is now up. Let me know if you need anything else. Happy to help!
